version: '3'

services:

  employee-crud-api-db:
    image: mongo
    restart: always
    container_name: employee-crud-api-db
    ports:
      - 27017:27017 
    volumes:
      - employee-crud-api-db:/data/db
    networks: 
      - employee-crud-api-network

  employee-crud-api-app:
    image: mish/employee-crud-api-app:dev
    build: 
      context: .
      # target: dev
    container_name: employee-crud-api-app
    restart: always
    volumes: 
      - .:/app
    ports:
      - "5000:5000"
      # - "3000:3000"
    depends_on:
      - employee-crud-api-db
    environment:
      - MONGODB_URI=mongodb://employee-crud-api-db/employee-crud-api-db
    networks: 
      - employee-crud-api-network

volumes: 
  employee-crud-api-db:
    # - employee-crud-api-db

networks: 
  employee-crud-api-network:
    # - employee-crud-api-network